macro(_CompileString2 variable separator item)
    set(${variable} ${item})
    foreach(word IN ITEMS ${ARGN})
        set(${variable} "${${variable}}${separator}${word}")
    endforeach()
endmacro()

macro(CompileString variable separator)
    if (${ARGC} GREATER 2)
        _CompileString2(${variable} ${separator} ${ARGN})
    else()
        set(${variable} "${ARGN}")
    endif()
endmacro()
